import type { Match, Team, User } from "@prisma/client";
import { PrismaClient } from "@prisma/client";

const db = new PrismaClient();

const seedRanking = {
  groupPoints: 0,
  playoffPoints: 0,
  totalPoints: 0,
};

const seedUserTeam = {
  points: 0,
  goalDifference: 0,
};

const seedStadiums = [
  {
    id: "khalifa-international-stadium",
    name: "Khalifa International Stadium",
  },
  { id: "al-thumama-stadium", name: "Al Thumama Stadium" },
  { id: "al-bayt-stadium", name: "Al Bayt Stadium" },
  { id: "lusail-iconic-stadium", name: "Lusail Iconic Stadium" },
  { id: "stadium-974", name: "Stadium 974" },
  { id: "education-city-stadium", name: "Education City Stadium" },
  { id: "ahmad-bin-ali-stadium", name: "Ahmad Bin Ali Stadium" },
  { id: "al-janoub-stadium", name: "Al Janoub Stadium" },
];

const seedGroups = [
  { id: "group-a", name: "A" },
  { id: "group-b", name: "B" },
  { id: "group-c", name: "C" },
  { id: "group-d", name: "D" },
  { id: "group-e", name: "E" },
  { id: "group-f", name: "F" },
  { id: "group-g", name: "G" },
  { id: "group-h", name: "H" },
];

const seedPlayoffs = [
  { id: "round-of-16", name: "Round of 16" },
  { id: "quarter-finals", name: "Quarter-finals" },
  { id: "semi-finals", name: "Semi-finals" },
  { id: "third-place", name: "Third place" },
  { id: "final", name: "Final" },
];

const seedStages = [
  { id: "group", name: "Group Stage" },
  { id: "playoff", name: "Playoff Stage" },
];

const seedTeams = [
  { id: "qatar", name: "Qatar", groupId: "group-a" },
  { id: "senegal", name: "Senegal", groupId: "group-a" },
  { id: "ecuador", name: "Ecuador", groupId: "group-a" },
  { id: "netherlands", name: "Netherlands", groupId: "group-a" },

  { id: "england", name: "England", groupId: "group-b" },
  { id: "iran", name: "Iran", groupId: "group-b" },
  { id: "usa", name: "USA", groupId: "group-b" },
  { id: "wales", name: "Wales", groupId: "group-b" },

  { id: "poland", name: "Poland", groupId: "group-c" },
  { id: "mexico", name: "Mexico", groupId: "group-c" },
  { id: "argentina", name: "Argentina", groupId: "group-c" },
  { id: "saudi-arabia", name: "Saudi Arabia", groupId: "group-c" },

  { id: "france", name: "France", groupId: "group-d" },
  { id: "australia", name: "Australia", groupId: "group-d" },
  { id: "denmark", name: "Denmark", groupId: "group-d" },
  { id: "tunisia", name: "Tunisia", groupId: "group-d" },

  { id: "spain", name: "Spain", groupId: "group-e" },
  { id: "costa-rica", name: "Costa Rica", groupId: "group-e" },
  { id: "germany", name: "Germany", groupId: "group-e" },
  { id: "japan", name: "Japan", groupId: "group-e" },

  { id: "belgium", name: "Belgium", groupId: "group-f" },
  { id: "canada", name: "Canada", groupId: "group-f" },
  { id: "morocco", name: "Morocco", groupId: "group-f" },
  { id: "croatia", name: "Croatia", groupId: "group-f" },

  { id: "brazil", name: "Brazil", groupId: "group-g" },
  { id: "serbia", name: "Serbia", groupId: "group-g" },
  { id: "switzerland", name: "Switzerland", groupId: "group-g" },
  { id: "cameroon", name: "Cameroon", groupId: "group-g" },

  { id: "portugal", name: "Portugal", groupId: "group-h" },
  { id: "ghana", name: "Ghana", groupId: "group-h" },
  { id: "uruguay", name: "Uruguay", groupId: "group-h" },
  { id: "south-korea", name: "South Korea", groupId: "group-h" },
];

const seedPlayers = [
  { name: "Wojciech Szczęsny", teamId: "poland" },
  { name: "Matty Cash", teamId: "poland" },
  { name: "Artur Jędrzejczyk", teamId: "poland" },
  { name: "Mateusz Wieteska", teamId: "poland" },
  { name: "Jan Bednarek", teamId: "poland" },
  { name: "Krystian Bielik", teamId: "poland" },
  { name: "Arkadiusz Milik", teamId: "poland" },
  { name: "Damian Szymański", teamId: "poland" },
  { name: "Robert Lewandowski", teamId: "poland" },
  { name: "Grzegorz Krychowiak", teamId: "poland" },
  { name: "Kamil Grosicki", teamId: "poland" },
  { name: "Łukasz Skorupski", teamId: "poland" },
  { name: "Jakub Kamiński", teamId: "poland" },
  { name: "Jakub Kiwior", teamId: "poland" },
  { name: "Kamil Glik", teamId: "poland" },
  { name: "Karol Świderski", teamId: "poland" },
  { name: "Szymon Żurkowski", teamId: "poland" },
  { name: "Bartosz Bereszyński", teamId: "poland" },
  { name: "Sebastian Szymański", teamId: "poland" },
  { name: "Piotr Zieliński", teamId: "poland" },
  { name: "Nicola Zalewski", teamId: "poland" },
  { name: "Kamil Grabara", teamId: "poland" },
  { name: "Krzyszof Piątek", teamId: "poland" },
  { name: "Przemysław Frankowski", teamId: "poland" },
  { name: "Robert Gumny", teamId: "poland" },
  { name: "Michał Skóraś", teamId: "poland" },

  { name: "Alfredo Talavera", teamId: "mexico" },
  { name: "Nestor Araujo", teamId: "mexico" },
  { name: "Cesar Montes", teamId: "mexico" },
  { name: "Edson Alvarez", teamId: "mexico" },
  { name: "Johan Vasquez", teamId: "mexico" },
  { name: "Gerardo Arteaga", teamId: "mexico" },
  { name: "Luis Romo", teamId: "mexico" },
  { name: "Carlos Rodriguez", teamId: "mexico" },
  { name: "Raul Jimenez", teamId: "mexico" },
  { name: "Alexis Vega", teamId: "mexico" },
  { name: "Rogelio Funes Mori", teamId: "mexico" },
  { name: "Rodolfo Cota", teamId: "mexico" },
  { name: "Guillermo Ochoa", teamId: "mexico" },
  { name: "Erick Gutierrez", teamId: "mexico" },
  { name: "Hector Moreno", teamId: "mexico" },
  { name: "Hector Herrera", teamId: "mexico" },
  { name: "Orbelin Pineda", teamId: "mexico" },
  { name: "Andres Guardado", teamId: "mexico" },
  { name: "Jorge Sanchez", teamId: "mexico" },
  { name: "Henry Martin", teamId: "mexico" },
  { name: "Uriel Antuna", teamId: "mexico" },
  { name: "Hirving Lozano", teamId: "mexico" },
  { name: "Jesus Gallardo", teamId: "mexico" },
  { name: "Luis Chavez", teamId: "mexico" },
  { name: "Roberto Alvarado", teamId: "mexico" },
  { name: "Kevin Alvarez", teamId: "mexico" },

  { name: "Hernan Galindez", teamId: "ecuador" },
  { name: "Felix Torres", teamId: "ecuador" },
  { name: "Piero Hincapie", teamId: "ecuador" },
  { name: "Roberto Arboleda", teamId: "ecuador" },
  { name: "Jose Cifuentes", teamId: "ecuador" },
  { name: "William Pacho", teamId: "ecuador" },
  { name: "Pervis Estupinian", teamId: "ecuador" },
  { name: "Carlos Gruezo", teamId: "ecuador" },
  { name: "Ayrton Preciado", teamId: "ecuador" },
  { name: "Romario Ibarra", teamId: "ecuador" },
  { name: "Michael Estrada", teamId: "ecuador" },
  { name: "Moises Ramirez", teamId: "ecuador" },
  { name: "Enner Valencia", teamId: "ecuador" },
  { name: "Xavier Arreaga", teamId: "ecuador" },
  { name: "Angel Mena", teamId: "ecuador" },
  { name: "Jeremy Sarmiento", teamId: "ecuador" },
  { name: "Angelo Preciado", teamId: "ecuador" },
  { name: "Diego Palacios", teamId: "ecuador" },
  { name: "Gonzalo Plata", teamId: "ecuador" },
  { name: "Sebas Mendez", teamId: "ecuador" },
  { name: "Alan Franco", teamId: "ecuador" },
  { name: "Alexander Dominguez", teamId: "ecuador" },
  { name: "Moises Caicedo", teamId: "ecuador" },
  { name: "Djorkaeff Reasco", teamId: "ecuador" },
  { name: "Jackson Porozo", teamId: "ecuador" },
  { name: "Kevin Rodriguez", teamId: "ecuador" },

  { name: "Remko Pasveer", teamId: "netherlands" },
  { name: "Jurrien Timber", teamId: "netherlands" },
  { name: "Matthijs de Ligt", teamId: "netherlands" },
  { name: "Virgil van Dijk", teamId: "netherlands" },
  { name: "Nathan Ake", teamId: "netherlands" },
  { name: "Stefan de Vrij", teamId: "netherlands" },
  { name: "Steven Bergwijn", teamId: "netherlands" },
  { name: "Cody Gakpo", teamId: "netherlands" },
  { name: "Luuk de Jong", teamId: "netherlands" },
  { name: "Memphis Depay", teamId: "netherlands" },
  { name: "Steven Berghuis", teamId: "netherlands" },
  { name: "Noa Lang", teamId: "netherlands" },
  { name: "Justin Bijlow", teamId: "netherlands" },
  { name: "Davy Klaassen", teamId: "netherlands" },
  { name: "Marten de Roon", teamId: "netherlands" },
  { name: "Tyrell Malacia", teamId: "netherlands" },
  { name: "Daley Blind", teamId: "netherlands" },
  { name: "Vincent Janssen", teamId: "netherlands" },
  { name: "Wout Weghorst", teamId: "netherlands" },
  { name: "Teun Koopmeiners", teamId: "netherlands" },
  { name: "Frenkie de Jong", teamId: "netherlands" },
  { name: "Denzel Dumfries", teamId: "netherlands" },
  { name: "Andries Noppert", teamId: "netherlands" },
  { name: "Kenneth Taylor", teamId: "netherlands" },
  { name: "Xavi Simons", teamId: "netherlands" },
  { name: "Jeremie Frimpong", teamId: "netherlands" },

  { name: "Saad Al-Sheeb", teamId: "qatar" },
  { name: "Ro-Ro", teamId: "qatar" },
  { name: "Abdelkarim Hassan", teamId: "qatar" },
  { name: "Mohammed Waad", teamId: "qatar" },
  { name: "Terek Salman", teamId: "qatar" },
  { name: "Abdulaziz Hatem", teamId: "qatar" },
  { name: "Ahmed Alaaeldin", teamId: "qatar" },
  { name: "Ali Assadalla", teamId: "qatar" },
  { name: "Mohammed Muntari", teamId: "qatar" },
  { name: "Hassan Al-Haydos", teamId: "qatar" },
  { name: "Akram Afif", teamId: "qatar" },
  { name: "Karim Boudiaf", teamId: "qatar" },
  { name: "Musab Kheder", teamId: "qatar" },
  { name: "Homam Ahmed", teamId: "qatar" },
  { name: "Bassam Al-Rawi", teamId: "qatar" },
  { name: "Boualem Khoukhi", teamId: "qatar" },
  { name: "Ismaeel Mohammad", teamId: "qatar" },
  { name: "Khalid Muneer", teamId: "qatar" },
  { name: "Almoez Ali", teamId: "qatar" },
  { name: "Salem Al-Hajri", teamId: "qatar" },
  { name: "Yousef Hassan", teamId: "qatar" },
  { name: "Meshaal Barsham", teamId: "qatar" },
  { name: "Assim Madibo", teamId: "qatar" },
  { name: "Naif Al-Hadharmi", teamId: "qatar" },
  { name: "Jassem Gaber", teamId: "qatar" },
  { name: "Mostafa Meshaal", teamId: "qatar" },

  { name: "Edouard Mendy", teamId: "senegal" },
  { name: "Ismail Jakobs", teamId: "senegal" },
  { name: "Kalidou Koulibaly", teamId: "senegal" },
  { name: "Abdou Diallo", teamId: "senegal" },
  { name: "Idrissa Gueye", teamId: "senegal" },
  { name: "Nampalys Mendy", teamId: "senegal" },
  { name: "Youssouf Sabaly", teamId: "senegal" },
  { name: "Cheikhou Kouyate", teamId: "senegal" },
  { name: "Iliman Ndiaye", teamId: "senegal" },
  { name: "Sadio Mane", teamId: "senegal" },
  { name: "Formose Mendy", teamId: "senegal" },
  { name: "Pape Abou Cisse", teamId: "senegal" },
  { name: "Pape Gueye", teamId: "senegal" },
  { name: "Moustapha Name", teamId: "senegal" },
  { name: "Krepin Diatta", teamId: "senegal" },
  { name: "Pathe Ciss", teamId: "senegal" },
  { name: "Pape Matar Sarr", teamId: "senegal" },
  { name: "Ismaila Sarr", teamId: "senegal" },
  { name: "Famara Diedhiou", teamId: "senegal" },
  { name: "Bamba Dieng", teamId: "senegal" },
  { name: "Boulaye Dia", teamId: "senegal" },
  { name: "Fode Ballo-Toure", teamId: "senegal" },
  { name: "Seny Dieng", teamId: "senegal" },
  { name: "Mamadou Loum", teamId: "senegal" },
  { name: "Nicolas Jackson", teamId: "senegal" },
  { name: "Alfred Gomis", teamId: "senegal" },

  { name: "Jordan Pickford", teamId: "england" },
  { name: "Kyle Walker", teamId: "england" },
  { name: "Luke Shaw", teamId: "england" },
  { name: "Declan Rice", teamId: "england" },
  { name: "John Stones", teamId: "england" },
  { name: "Harry Maguire", teamId: "england" },
  { name: "Jack Grealish", teamId: "england" },
  { name: "Jordan Henderson", teamId: "england" },
  { name: "Harry Kane", teamId: "england" },
  { name: "Raheem Sterling", teamId: "england" },
  { name: "Marcus Rashford", teamId: "england" },
  { name: "Kieran Trippier", teamId: "england" },
  { name: "Nick Pope", teamId: "england" },
  { name: "Kalvin Phillips", teamId: "england" },
  { name: "Eric Dier", teamId: "england" },
  { name: "Conor Coady", teamId: "england" },
  { name: "Bukayo Saka", teamId: "england" },
  { name: "Trent Alexander-Arnold", teamId: "england" },
  { name: "Mason Mount", teamId: "england" },
  { name: "Phil Foden", teamId: "england" },
  { name: "Ben White", teamId: "england" },
  { name: "Jude Bellingham", teamId: "england" },
  { name: "Aaron Ramsdale", teamId: "england" },
  { name: "Callum Wilson", teamId: "england" },
  { name: "James Maddison", teamId: "england" },
  { name: "Conor Gallagher", teamId: "england" },

  { name: "Alireza Bejranwand", teamId: "iran" },
  { name: "Sadegh Moharrami", teamId: "iran" },
  { name: "Ehsan Hadzsafi", teamId: "iran" },
  { name: "Shojae Khalilzadeh", teamId: "iran" },
  { name: "Milad Mohammadi", teamId: "iran" },
  { name: "Said Ezzatollahi", teamId: "iran" },
  { name: "Alireza Jahanbakhsh", teamId: "iran" },
  { name: "Morteza Puraligandzi", teamId: "iran" },
  { name: "Mahdi Taremi", teamId: "iran" },
  { name: "Karim Ansarifard", teamId: "iran" },
  { name: "Wahid Amiri", teamId: "iran" },
  { name: "Payam Niazmand", teamId: "iran" },
  { name: "Hosejn Kananizadegan", teamId: "iran" },
  { name: "Saman Ghoddus", teamId: "iran" },
  { name: "Ruzbe Czeszmi", teamId: "iran" },
  { name: "Mahdi Torabi", teamId: "iran" },
  { name: "Ali Gholizadeh", teamId: "iran" },
  { name: "Ali Karimi", teamId: "iran" },
  { name: "Madzid Hosejni", teamId: "iran" },
  { name: "Sardar Azmun", teamId: "iran" },
  { name: "Ahmad Nurollahi", teamId: "iran" },
  { name: "Amir Abedzade", teamId: "iran" },
  { name: "Ramin Rezajijan", teamId: "iran" },
  { name: "Hossein Hosseini", teamId: "iran" },
  { name: "Abolfazi Jalali", teamId: "iran" },

  { name: "Matt Turner", teamId: "usa" },
  { name: "Sergino Dest", teamId: "usa" },
  { name: "Walker Zimmerman", teamId: "usa" },
  { name: "Tyler Adams", teamId: "usa" },
  { name: "Antonee Robinson", teamId: "usa" },
  { name: "Yunus Musah", teamId: "usa" },
  { name: "Giovanni Reyna", teamId: "usa" },
  { name: "Weston McKennie", teamId: "usa" },
  { name: "Jesus Ferreira", teamId: "usa" },
  { name: "Christian Pulisic", teamId: "usa" },
  { name: "Brenden Aaronson", teamId: "usa" },
  { name: "Ethan Horvath", teamId: "usa" },
  { name: "Tim Ream", teamId: "usa" },
  { name: "Luca de la Torre", teamId: "usa" },
  { name: "Aaron Long", teamId: "usa" },
  { name: "Jordan Morris", teamId: "usa" },
  { name: "Cristian Roldan", teamId: "usa" },
  { name: "Shaq Moore", teamId: "usa" },
  { name: "Cameron Carter-Vickers", teamId: "usa" },
  { name: "Timothy Weah", teamId: "usa" },
  { name: "DeAndre Yedlin", teamId: "usa" },
  { name: "Kellyn Acosta", teamId: "usa" },
  { name: "Josh Sargent", teamId: "usa" },
  { name: "Sean Johnson", teamId: "usa" },
  { name: "Joe Scally", teamId: "usa" },
  { name: "Haji Wright", teamId: "usa" },

  { name: "Wayne Hennessey", teamId: "wales" },
  { name: "Chris Gunter", teamId: "wales" },
  { name: "Neco Williams", teamId: "wales" },
  { name: "Ben Davies", teamId: "wales" },
  { name: "Chris Mepham", teamId: "wales" },
  { name: "Joe Rodon", teamId: "wales" },
  { name: "Joe Allen", teamId: "wales" },
  { name: "Harry Wilson", teamId: "wales" },
  { name: "Brennan Johnson", teamId: "wales" },
  { name: "Aaron Ramsey", teamId: "wales" },
  { name: "Gareth Bale", teamId: "wales" },
  { name: "Danny Ward", teamId: "wales" },
  { name: "Kieffer Moore", teamId: "wales" },
  { name: "Connor Roberts", teamId: "wales" },
  { name: "Ethan Ampadu", teamId: "wales" },
  { name: "Joe Morrell", teamId: "wales" },
  { name: "Tom Lockyer", teamId: "wales" },
  { name: "Johnny Williams", teamId: "wales" },
  { name: "Mark Harris", teamId: "wales" },
  { name: "Daniel James", teamId: "wales" },
  { name: "Adam Davies", teamId: "wales" },
  { name: "Sorba Thomas", teamId: "wales" },
  { name: "Dylan Levitt", teamId: "wales" },
  { name: "Ben Cabango", teamId: "wales" },
  { name: "Rubin Colwill", teamId: "wales" },
  { name: "Matthew Smith", teamId: "wales" },

  { name: "Franco Armani", teamId: "argentina" },
  { name: "Juan Foyth", teamId: "argentina" },
  { name: "Nicolas Tagliafico", teamId: "argentina" },
  { name: "Gonzalo Montiel", teamId: "argentina" },
  { name: "Leandro Paredes", teamId: "argentina" },
  { name: "German Pezzella", teamId: "argentina" },
  { name: "Rodrigo De Paul", teamId: "argentina" },
  { name: "Marcos Acuna", teamId: "argentina" },
  { name: "Julian Alvarez", teamId: "argentina" },
  { name: "Leo Messi", teamId: "argentina" },
  { name: "Angel Di Maria", teamId: "argentina" },
  { name: "Geronimo Rulli", teamId: "argentina" },
  { name: "Cristian Romero", teamId: "argentina" },
  { name: "Exequiel Palacios", teamId: "argentina" },
  { name: "Nicolas Gonzalez", teamId: "argentina" },
  { name: "Joaquin Correa", teamId: "argentina" },
  { name: "Papu Gomez", teamId: "argentina" },
  { name: "Guido Rodriguez", teamId: "argentina" },
  { name: "Nicolas Otamendi", teamId: "argentina" },
  { name: "Alexis Mac Allister", teamId: "argentina" },
  { name: "Paulo Dybala", teamId: "argentina" },
  { name: "Lautaro Martinez", teamId: "argentina" },
  { name: "Enzo Fernandez", teamId: "argentina" },
  { name: "Lisandro Martinez", teamId: "argentina" },
  { name: "Nahuel Molina", teamId: "argentina" },
  { name: "Emiliano Martinez", teamId: "argentina" },

  { name: "Mohammed Al-Rubaie", teamId: "saudi-arabia" },
  { name: "Sultan Al-Ghanam", teamId: "saudi-arabia" },
  { name: "Abdullah Madu", teamId: "saudi-arabia" },
  { name: "Abdulelah Al-Amri", teamId: "saudi-arabia" },
  { name: "Ali Al-Bulaihi", teamId: "saudi-arabia" },
  { name: "Mohammed Al-Breik", teamId: "saudi-arabia" },
  { name: "Salman Al-Faraj", teamId: "saudi-arabia" },
  { name: "Abdulellah Al-Malki", teamId: "saudi-arabia" },
  { name: "Firas Al-Buraikan", teamId: "saudi-arabia" },
  { name: "Salem Al-Dawsari", teamId: "saudi-arabia" },
  { name: "Saleh Al-Shahrani", teamId: "saudi-arabia" },
  { name: "Abdullah Otayf", teamId: "saudi-arabia" },
  { name: "Ali Al-Hassan", teamId: "saudi-arabia" },
  { name: "Sami Al-Najei", teamId: "saudi-arabia" },
  { name: "Hassan Tambakti", teamId: "saudi-arabia" },
  { name: "Nawaf Al-Abed", teamId: "saudi-arabia" },
  { name: "Hattan Bahebri", teamId: "saudi-arabia" },
  { name: "Abdulrahman Al-Aboud", teamId: "saudi-arabia" },
  { name: "Mohammed Al-Owais", teamId: "saudi-arabia" },
  { name: "Nawaf Al-Aqidi", teamId: "saudi-arabia" },
  { name: "Nasser Al-Dawsari", teamId: "saudi-arabia" },
  { name: "Haitham Asiri", teamId: "saudi-arabia" },
  { name: "Riyadh Sharahili", teamId: "saudi-arabia" },
  { name: "Saud Abdulhamid", teamId: "saudi-arabia" },
  { name: "Mohammed Kanno", teamId: "saudi-arabia" },
  { name: "Saleh Al-Shehri", teamId: "saudi-arabia" },

  { name: "Matthew Ryan", teamId: "australia" },
  { name: "Milos Degenek", teamId: "australia" },
  { name: "Nathaniel Atkinson", teamId: "australia" },
  { name: "Kye Rowles", teamId: "australia" },
  { name: "Fran Karacic", teamId: "australia" },
  { name: "Martin Boyle", teamId: "australia" },
  { name: "Mathew Leckie", teamId: "australia" },
  { name: "Bailey Wright", teamId: "australia" },
  { name: "Jamie Maclaren", teamId: "australia" },
  { name: "Ajdin Hrustic", teamId: "australia" },
  { name: "Awer Mabil", teamId: "australia" },
  { name: "Andrew Redmayne", teamId: "australia" },
  { name: "Aaron Mooy", teamId: "australia" },
  { name: "Riley McGree", teamId: "australia" },
  { name: "Mitchell Duke", teamId: "australia" },
  { name: "Aziz Behich", teamId: "australia" },
  { name: "Cameron Devlin", teamId: "australia" },
  { name: "Danny Vukovic", teamId: "australia" },
  { name: "Harry Souttar", teamId: "australia" },
  { name: "Thomas Deng", teamId: "australia" },
  { name: "Garang Kuol", teamId: "australia" },
  { name: "Jackson Irvine", teamId: "australia" },
  { name: "Craig Goodwin", teamId: "australia" },
  { name: "Joel King", teamId: "australia" },
  { name: "Jason Cummings", teamId: "australia" },
  { name: "Keanu Baccus", teamId: "australia" },

  { name: "Kasper Schmeichel", teamId: "denmark" },
  { name: "Joachim Andersen", teamId: "denmark" },
  { name: "Victor Nelsson", teamId: "denmark" },
  { name: "Simon Kjaer", teamId: "denmark" },
  { name: "Joakim Maehle", teamId: "denmark" },
  { name: "Andreas Christensen", teamId: "denmark" },
  { name: "Mathias Jensen", teamId: "denmark" },
  { name: "Thomas Delaney", teamId: "denmark" },
  { name: "Martin Braithwaite", teamId: "denmark" },
  { name: "Christian Eriksen", teamId: "denmark" },
  { name: "Andreas Skov Olsen", teamId: "denmark" },
  { name: "Kasper Dolberg", teamId: "denmark" },
  { name: "Rasmus Kristensen", teamId: "denmark" },
  { name: "Mikkel Damsgaard", teamId: "denmark" },
  { name: "Christian Norgaard", teamId: "denmark" },
  { name: "Oliver Christensen", teamId: "denmark" },
  { name: "Jens Stryger Larsen", teamId: "denmark" },
  { name: "Daniel Wass", teamId: "denmark" },
  { name: "Jonas Wind", teamId: "denmark" },
  { name: "Tussuf Poulsen", teamId: "denmark" },
  { name: "Andreas Cornelius", teamId: "denmark" },
  { name: "Frederik Ronnow", teamId: "denmark" },
  { name: "Pierre Hojbjerg", teamId: "denmark" },
  { name: "Robert Skov", teamId: "denmark" },
  { name: "Jasper Lindstrom", teamId: "denmark" },
  { name: "Alexander Bah", teamId: "denmark" },

  { name: "Hugo Lloris", teamId: "france" },
  { name: "Benjamin Pavard", teamId: "france" },
  { name: "Axel Disasi", teamId: "france" },
  { name: "Raphael Varane", teamId: "france" },
  { name: "Jules Kounde", teamId: "france" },
  { name: "Matteo Guendouzi", teamId: "france" },
  { name: "Antoine Griezmann", teamId: "france" },
  { name: "Aurelien Tchouameni", teamId: "france" },
  { name: "Olivier Giroud", teamId: "france" },
  { name: "Kylian Mbappe", teamId: "france" },
  { name: "Ousmane Dembele", teamId: "france" },
  { name: "Randal Kolo Muani", teamId: "france" },
  { name: "Youssouf Fofana", teamId: "france" },
  { name: "Adrien Rabiot", teamId: "france" },
  { name: "Jordan Veretout", teamId: "france" },
  { name: "Steve Mandanda", teamId: "france" },
  { name: "William Saliba", teamId: "france" },
  { name: "Dayot Upamecano", teamId: "france" },
  { name: "Karim Benzema", teamId: "france" },
  { name: "Kingsley Coman", teamId: "france" },
  { name: "Lucas Hernandez", teamId: "france" },
  { name: "Theo Hernandez", teamId: "france" },
  { name: "Alphonse Areola", teamId: "france" },
  { name: "Ibrahima Konate", teamId: "france" },
  { name: "Edouardo Camavinga", teamId: "france" },
  { name: "Marcus Thuram", teamId: "france" },

  { name: "Aymen Mathlouthi", teamId: "tunisia" },
  { name: "Bilel Ifa", teamId: "tunisia" },
  { name: "Montassar Talbi", teamId: "tunisia" },
  { name: "Yassine Meriah", teamId: "tunisia" },
  { name: "Nader Ghandri", teamId: "tunisia" },
  { name: "Dylan Bronn", teamId: "tunisia" },
  { name: "Youssef Msakni", teamId: "tunisia" },
  { name: "Hannibal Mejbri", teamId: "tunisia" },
  { name: "Issam Jebali", teamId: "tunisia" },
  { name: "Wahbi Khazri", teamId: "tunisia" },
  { name: "Taha Yassine Khenissi", teamId: "tunisia" },
  { name: "Ali Maaloul", teamId: "tunisia" },
  { name: "Ferjani Sassi", teamId: "tunisia" },
  { name: "Aissa Laidouni", teamId: "tunisia" },
  { name: "Mohamed Ali Ben Romdhane", teamId: "tunisia" },
  { name: "Ellyes Skhiri", teamId: "tunisia" },
  { name: "Ghailene Chaalali", teamId: "tunisia" },
  { name: "Seifeddine Jaziri", teamId: "tunisia" },
  { name: "Mohamed Drager", teamId: "tunisia" },
  { name: "Wajdi Kechrida", teamId: "tunisia" },
  { name: "Bechir Ben Said", teamId: "tunisia" },
  { name: "Naim Sliti", teamId: "tunisia" },
  { name: "Ali Abdi", teamId: "tunisia" },
  { name: "Anis Ben Slimane", teamId: "tunisia" },
  { name: "Mouzez Hassen", teamId: "tunisia" },
  { name: "Aymen Dahmen", teamId: "tunisia" },

  { name: "Keylor Navas", teamId: "costa-rica" },
  { name: "Daniel Chacon", teamId: "costa-rica" },
  { name: "Juan Pablo Vargas", teamId: "costa-rica" },
  { name: "Keysher Fuller", teamId: "costa-rica" },
  { name: "Celso Borges", teamId: "costa-rica" },
  { name: "Oscar Duarte", teamId: "costa-rica" },
  { name: "Anthony Contreras", teamId: "costa-rica" },
  { name: "Bryan Oviedo", teamId: "costa-rica" },
  { name: "Jewison Bennette", teamId: "costa-rica" },
  { name: "Bryan Ruiz", teamId: "costa-rica" },
  { name: "Johan Venegas", teamId: "costa-rica" },
  { name: "Joel Campbell", teamId: "costa-rica" },
  { name: "Gerson Torres", teamId: "costa-rica" },
  { name: "Youstin Salas", teamId: "costa-rica" },
  { name: "Francisco Calvo", teamId: "costa-rica" },
  { name: "Carlos Martinez", teamId: "costa-rica" },
  { name: "Yeltsin Tejeda", teamId: "costa-rica" },
  { name: "Esteban Alvarado", teamId: "costa-rica" },
  { name: "Kendall Waston", teamId: "costa-rica" },
  { name: "Brandon Aguilera", teamId: "costa-rica" },
  { name: "Douglas lopez", teamId: "costa-rica" },
  { name: "Ronald Matarrita", teamId: "costa-rica" },
  { name: "Patrick Sequeria", teamId: "costa-rica" },
  { name: "Roan Wilson", teamId: "costa-rica" },
  { name: "Anthony Hernandez", teamId: "costa-rica" },
  { name: "Alvaro Zamora", teamId: "costa-rica" },

  { name: "Manuel Neuer", teamId: "germany" },
  { name: "Antonio Rudiger", teamId: "germany" },
  { name: "David Raum", teamId: "germany" },
  { name: "Matthias Ginter", teamId: "germany" },
  { name: "Thilo Kehrer", teamId: "germany" },
  { name: "Joshua Kimmich", teamId: "germany" },
  { name: "Kai Havertz", teamId: "germany" },
  { name: "Leon Goretzka", teamId: "germany" },
  { name: "Niclas Fullkrug", teamId: "germany" },
  { name: "Serge Gnabry", teamId: "germany" },
  { name: "Mario Gotze", teamId: "germany" },
  { name: "Kevin Trapp", teamId: "germany" },
  { name: "Thomas Muller", teamId: "germany" },
  { name: "Jamal Musiala", teamId: "germany" },
  { name: "Niklas Sule", teamId: "germany" },
  { name: "Lukas Klostermann", teamId: "germany" },
  { name: "Julian Brandt", teamId: "germany" },
  { name: "Jonas Hofmann", teamId: "germany" },
  { name: "Leroy Sane", teamId: "germany" },
  { name: "Christian Gunter", teamId: "germany" },
  { name: "Ilkay Gundogan", teamId: "germany" },
  { name: "Marc-Andre ter Stegen", teamId: "germany" },
  { name: "Nico Schlotterbeck", teamId: "germany" },
  { name: "Karim Adeyemi", teamId: "germany" },
  { name: "Armel Bella-Kotchap", teamId: "germany" },
  { name: "Youssoufa Moukoko", teamId: "germany" },

  { name: "Eiji Kawashima", teamId: "japan" },
  { name: "Miki Yamane", teamId: "japan" },
  { name: "Shogo Taniguchi", teamId: "japan" },
  { name: "Ko Itakura", teamId: "japan" },
  { name: "Yuto Nagatomo", teamId: "japan" },
  { name: "Wataru Endo", teamId: "japan" },
  { name: "Gaku Shibasaki", teamId: "japan" },
  { name: "Ritsu Doan", teamId: "japan" },
  { name: "Kaoru Mitoma", teamId: "japan" },
  { name: "Takumi Minamino", teamId: "japan" },
  { name: "Takefusa Kubo", teamId: "japan" },
  { name: "Shuichi Gonda", teamId: "japan" },
  { name: "Hidemasa Morita", teamId: "japan" },
  { name: "Junya Ito", teamId: "japan" },
  { name: "Daichi Kamada", teamId: "japan" },
  { name: "Takehiro Tomiyasu", teamId: "japan" },
  { name: "Ao Tanaka", teamId: "japan" },
  { name: "Takuma Asano", teamId: "japan" },
  { name: "Hiroki Sakai", teamId: "japan" },
  { name: "Shuto Machino", teamId: "japan" },
  { name: "Ayase Ueda", teamId: "japan" },
  { name: "Maya Yoshida", teamId: "japan" },
  { name: "Daniel Schmidt", teamId: "japan" },
  { name: "Yuki Soma", teamId: "japan" },
  { name: "Daizen Maeda", teamId: "japan" },
  { name: "Hiroki Ito", teamId: "japan" },

  { name: "Robert Sanchez", teamId: "spain" },
  { name: "Cesar Azpilicueta", teamId: "spain" },
  { name: "Eric Garcia", teamId: "spain" },
  { name: "Pau Torres", teamId: "spain" },
  { name: "Sergio Busquets", teamId: "spain" },
  { name: "Marcos Llorente", teamId: "spain" },
  { name: "Alvaro Morata", teamId: "spain" },
  { name: "Koke", teamId: "spain" },
  { name: "Gavi", teamId: "spain" },
  { name: "Marcos Asensio", teamId: "spain" },
  { name: "Ferran Torres", teamId: "spain" },
  { name: "Nico Williams", teamId: "spain" },
  { name: "David Raya", teamId: "spain" },
  { name: "Jose Gaya", teamId: "spain" },
  { name: "Hugo Guillamon", teamId: "spain" },
  { name: "Rodri", teamId: "spain" },
  { name: "Yeremi Pino", teamId: "spain" },
  { name: "Jordi Alba", teamId: "spain" },
  { name: "Carlos Soler", teamId: "spain" },
  { name: "Dani Carvajal", teamId: "spain" },
  { name: "Dani Olmo", teamId: "spain" },
  { name: "Pablo Sarabia", teamId: "spain" },
  { name: "Unai Simon", teamId: "spain" },
  { name: "Aymeric Laporte", teamId: "spain" },
  { name: "Ansu Fati", teamId: "spain" },
  { name: "Pedri", teamId: "spain" },

  { name: "Thibaut Courtois", teamId: "belgium" },
  { name: "Toby Alderweireld", teamId: "belgium" },
  { name: "Arthur Theate", teamId: "belgium" },
  { name: "Wout Faes", teamId: "belgium" },
  { name: "Jan Vertonghen", teamId: "belgium" },
  { name: "Axel Witsel", teamId: "belgium" },
  { name: "Kevin De Bruyne", teamId: "belgium" },
  { name: "Youri Tielemans", teamId: "belgium" },
  { name: "Romelu Lukaku", teamId: "belgium" },
  { name: "Eden Hazard", teamId: "belgium" },
  { name: "Yannick Carrasco", teamId: "belgium" },
  { name: "Simon Mignolet", teamId: "belgium" },
  { name: "Koen Casteels", teamId: "belgium" },
  { name: "Dries Mertens", teamId: "belgium" },
  { name: "Thomas Meunier", teamId: "belgium" },
  { name: "Thorgan Hazard", teamId: "belgium" },
  { name: "Leandro Trossard", teamId: "belgium" },
  { name: "Amadou Onana", teamId: "belgium" },
  { name: "Leander Dendoncker", teamId: "belgium" },
  { name: "Hans Vanaken", teamId: "belgium" },
  { name: "Timothy Castagne", teamId: "belgium" },
  { name: "Charles De Ketelaere", teamId: "belgium" },
  { name: "Michy Batshuayi", teamId: "belgium" },
  { name: "Lois Openda", teamId: "belgium" },
  { name: "Jeremy Doku", teamId: "belgium" },
  { name: "Zeno Debast", teamId: "belgium" },

  { name: "Dayne St. Clair", teamId: "canada" },
  { name: "Alistar Johnston", teamId: "canada" },
  { name: "Sam Adekugbe", teamId: "canada" },
  { name: "Kamal Miller", teamId: "canada" },
  { name: "Steven Vitoria", teamId: "canada" },
  { name: "Samuel Piette", teamId: "canada" },
  { name: "Stephen Eustaquio", teamId: "canada" },
  { name: "Liam Fraser", teamId: "canada" },
  { name: "Lucas Cavallini", teamId: "canada" },
  { name: "Junior Hoilett", teamId: "canada" },
  { name: "Tajon Buchanan", teamId: "canada" },
  { name: "Ike Ugbo", teamId: "canada" },
  { name: "Atiba Hutchinson", teamId: "canada" },
  { name: "Mark-Anthony Kaye", teamId: "canada" },
  { name: "Ismael Kone", teamId: "canada" },
  { name: "James Pantemis", teamId: "canada" },
  { name: "Cyle Larin", teamId: "canada" },
  { name: "Milan Borjan", teamId: "canada" },
  { name: "Alphonso Davies", teamId: "canada" },
  { name: "Jonathan David", teamId: "canada" },
  { name: "Richie Laryea", teamId: "canada" },
  { name: "Jonathan Osorio", teamId: "canada" },
  { name: "Liam Millar", teamId: "canada" },
  { name: "David Wotherspoon", teamId: "canada" },
  { name: "Derek Cornelius", teamId: "canada" },
  { name: "Joel Waterman", teamId: "canada" },

  { name: "Dominik Livakovic", teamId: "croatia" },
  { name: "Josip Stanisic", teamId: "croatia" },
  { name: "Borna Barisic", teamId: "croatia" },
  { name: "Ivan Perisic", teamId: "croatia" },
  { name: "Martin Erlic", teamId: "croatia" },
  { name: "Dejan Lovren", teamId: "croatia" },
  { name: "Lovro Majer", teamId: "croatia" },
  { name: "Mateo Kovacic", teamId: "croatia" },
  { name: "Andrej Kramaric", teamId: "croatia" },
  { name: "Luka Modric", teamId: "croatia" },
  { name: "Marcelo Brozovic", teamId: "croatia" },
  { name: "Ivo Grbic", teamId: "croatia" },
  { name: "Nikola Vlasic", teamId: "croatia" },
  { name: "Marko Livaja", teamId: "croatia" },
  { name: "Mario Pasalic", teamId: "croatia" },
  { name: "Bruno Petkovic", teamId: "croatia" },
  { name: "Ante Budimir", teamId: "croatia" },
  { name: "Mislav Orsic", teamId: "croatia" },
  { name: "Borna Sosa", teamId: "croatia" },
  { name: "Josko Gvardiol", teamId: "croatia" },
  { name: "Domagoj Vida", teamId: "croatia" },
  { name: "Josip Juranovic", teamId: "croatia" },
  { name: "Ivica Ivusic", teamId: "croatia" },
  { name: "Josip Sutalo", teamId: "croatia" },
  { name: "Luka Sucic", teamId: "croatia" },
  { name: "Kristijan Jakic", teamId: "croatia" },

  { name: "Yassine Bounou", teamId: "morocco" },
  { name: "Munir El Kajoui", teamId: "morocco" },
  { name: "Reda Tagnaouti", teamId: "morocco" },
  { name: "Achraf Hakimi", teamId: "morocco" },
  { name: "Noussair Mazraoui", teamId: "morocco" },
  { name: "Roman Saiss", teamId: "morocco" },
  { name: "Nayef Aguerd", teamId: "morocco" },
  { name: "Jawed El Yamiq", teamId: "morocco" },
  { name: "Achraf Dari", teamId: "morocco" },
  { name: "Yahya Attiat Allal", teamId: "morocco" },
  { name: "Badr Benaoun", teamId: "morocco" },
  { name: "Sofyan Amrabat", teamId: "morocco" },
  { name: "Selim Amallah", teamId: "morocco" },
  { name: "Azzedine Ounahi", teamId: "morocco" },
  { name: "Abdelhamid Sabiri", teamId: "morocco" },
  { name: "Yahya Jabrane", teamId: "morocco" },
  { name: "Bilal El Khannouss", teamId: "morocco" },
  { name: "Amine Harit", teamId: "morocco" },
  { name: "Ilaias Chair", teamId: "morocco" },
  { name: "Hakim Ziyech", teamId: "morocco" },
  { name: "Youssef En-Nesyri", teamId: "morocco" },
  { name: "Abde Ezzalzouli", teamId: "morocco" },
  { name: "Walid Cheddira", teamId: "morocco" },
  { name: "Zakaria Aboukhlal", teamId: "morocco" },
  { name: "Sofiane Boufal", teamId: "morocco" },
  { name: "Abderrazak Hamdallah", teamId: "morocco" },

  { name: "Alisson", teamId: "brazil" },
  { name: "Danilo", teamId: "brazil" },
  { name: "Thiago Silva", teamId: "brazil" },
  { name: "Marquinhos", teamId: "brazil" },
  { name: "Casemiro", teamId: "brazil" },
  { name: "Alex Sandro", teamId: "brazil" },
  { name: "Lucas Paqueta", teamId: "brazil" },
  { name: "Fred", teamId: "brazil" },
  { name: "Richarlison", teamId: "brazil" },
  { name: "Neymar", teamId: "brazil" },
  { name: "Raphinha", teamId: "brazil" },
  { name: "Weverton", teamId: "brazil" },
  { name: "Dani Alves", teamId: "brazil" },
  { name: "Eder Militao", teamId: "brazil" },
  { name: "Fabinho", teamId: "brazil" },
  { name: "Alex Telles", teamId: "brazil" },
  { name: "Bruno Guimaraes", teamId: "brazil" },
  { name: "Antony", teamId: "brazil" },
  { name: "Gabriel Jesus", teamId: "brazil" },
  { name: "Vinicius Junior", teamId: "brazil" },
  { name: "Rodrygo", teamId: "brazil" },
  { name: "Bremer", teamId: "brazil" },
  { name: "Ederson", teamId: "brazil" },
  { name: "Gabriel Martinelli", teamId: "brazil" },
  { name: "Pedro", teamId: "brazil" },
  { name: "Everton Ribeiro", teamId: "brazil" },

  { name: "Andre Onana", teamId: "cameroon" },
  { name: "Devis Epassy", teamId: "cameroon" },
  { name: "Simon Ngapandouetnbu", teamId: "cameroon" },
  { name: "Nicolas Nkoulou", teamId: "cameroon" },
  { name: "Collins Fai", teamId: "cameroon" },
  { name: "Nouhou Tolo", teamId: "cameroon" },
  { name: "Jean-Charles Castelletto", teamId: "cameroon" },
  { name: "Olivier Mbaizo", teamId: "cameroon" },
  { name: "Enzo Ebosse", teamId: "cameroon" },
  { name: "Christopher Wooh", teamId: "cameroon" },
  { name: "Andre Anguissa", teamId: "cameroon" },
  { name: "Pierre Kunde", teamId: "cameroon" },
  { name: "Samuel Gouet", teamId: "cameroon" },
  { name: "Martin Hongla", teamId: "cameroon" },
  { name: "Gael Ondoua", teamId: "cameroon" },
  { name: "Olivier Ntcham", teamId: "cameroon" },
  { name: "jerome Ngom Mbekeli", teamId: "cameroon" },
  { name: "Vincent Aboubakar", teamId: "cameroon" },
  { name: "Eric Maxim Choupo-Moting", teamId: "cameroon" },
  { name: "Karl Toko Ekambi", teamId: "cameroon" },
  { name: "Christian Bassogog", teamId: "cameroon" },
  { name: "Moumi Ngamaleu", teamId: "cameroon" },
  { name: "Jean-Pierre Nsame", teamId: "cameroon" },
  { name: "Bryan Mbeumo", teamId: "cameroon" },
  { name: "Georges-Kevin Nkoudou", teamId: "cameroon" },
  { name: "Souaibou Marou", teamId: "cameroon" },

  { name: "Marko Dmitrovic", teamId: "serbia" },
  { name: "Predrag Rajkovic", teamId: "serbia" },
  { name: "Vanja Milinkovic-Savic", teamId: "serbia" },
  { name: "Stefan Mitrovic", teamId: "serbia" },
  { name: "Nikola Milenkovic", teamId: "serbia" },
  { name: "Strahinja Pavlovic", teamId: "serbia" },
  { name: "Milos Veljkovic", teamId: "serbia" },
  { name: "Filip Mladenovic", teamId: "serbia" },
  { name: "Strahinja Erakovic", teamId: "serbia" },
  { name: "Srdjan Babic", teamId: "serbia" },
  { name: "Nemanja Gudelj", teamId: "serbia" },
  { name: "Sergej Milinkovic-Savic", teamId: "serbia" },
  { name: "Sasa Lukic", teamId: "serbia" },
  { name: "Marko Grujic", teamId: "serbia" },
  { name: "Filip Kostic", teamId: "serbia" },
  { name: "Uros Racic", teamId: "serbia" },
  { name: "Nemanja Maksimovic", teamId: "serbia" },
  { name: "Ivan Ilic", teamId: "serbia" },
  { name: "Andrija Zivkovic", teamId: "serbia" },
  { name: "Darko Lazovic", teamId: "serbia" },
  { name: "Dusan Tadic", teamId: "serbia" },
  { name: "Aleksandar Mitrovic", teamId: "serbia" },
  { name: "Dusan Vlahovic", teamId: "serbia" },
  { name: "Filip Duricic", teamId: "serbia" },
  { name: "Luka Jovic", teamId: "serbia" },
  { name: "Nemanja Radonjic", teamId: "serbia" },

  { name: "Yann Sommer", teamId: "switzerland" },
  { name: "Jonas Omlin", teamId: "switzerland" },
  { name: "Gregor Kobel", teamId: "switzerland" },
  { name: "Philipp Kohn", teamId: "switzerland" },
  { name: "Ricardo Rodriguez", teamId: "switzerland" },
  { name: "Fabian Schar", teamId: "switzerland" },
  { name: "Manuel Akanji", teamId: "switzerland" },
  { name: "Nico Elvedi", teamId: "switzerland" },
  { name: "Silvan Widmer", teamId: "switzerland" },
  { name: "Eray Comert", teamId: "switzerland" },
  { name: "Xherdan Shaqiri", teamId: "switzerland" },
  { name: "Granit Xhaka", teamId: "switzerland" },
  { name: "Remo Freuler", teamId: "switzerland" },
  { name: "Denis Zakaria", teamId: "switzerland" },
  { name: "Djibril Sow", teamId: "switzerland" },
  { name: "Renato Steffen", teamId: "switzerland" },
  { name: "Edimilson Fernandes", teamId: "switzerland" },
  { name: "Fabian Frei", teamId: "switzerland" },
  { name: "Michel Aebischer", teamId: "switzerland" },
  { name: "Ardon Jashari", teamId: "switzerland" },
  { name: "Fabian Rieder", teamId: "switzerland" },
  { name: "Haris Seferovic", teamId: "switzerland" },
  { name: "Breel Embolo", teamId: "switzerland" },
  { name: "Ruben Vargas", teamId: "switzerland" },
  { name: "Christian Fassnacht", teamId: "switzerland" },
  { name: "Noah Okafor", teamId: "switzerland" },
];

const seedGroupMatches = [
  /* --- Group A --- */
  {
    homeTeamId: "qatar",
    awayTeamId: "ecuador",
    groupId: "group-a",
    stadiumId: "al-bayt-stadium",
    startDate: new Date("2022-11-20T19:00:00"),
    stageId: "group",
  },
  {
    homeTeamId: "senegal",
    awayTeamId: "netherlands",
    groupId: "group-a",
    stadiumId: "al-thumama-stadium",
    startDate: new Date("2022-11-21T16:00:00"),
    stageId: "group",
  },
  {
    homeTeamId: "qatar",
    awayTeamId: "senegal",
    groupId: "group-a",
    stadiumId: "al-thumama-stadium",
    startDate: new Date("2022-11-25T16:00:00"),
    stageId: "group",
  },
  {
    homeTeamId: "netherlands",
    awayTeamId: "ecuador",
    groupId: "group-a",
    stadiumId: "khalifa-international-stadium",
    startDate: new Date("2022-11-25T19:00:00"),
    stageId: "group",
  },
  {
    homeTeamId: "ecuador",
    awayTeamId: "senegal",
    groupId: "group-a",
    stadiumId: "khalifa-international-stadium",
    startDate: new Date("2022-11-29T18:00:00"),
    stageId: "group",
  },
  {
    homeTeamId: "netherlands",
    awayTeamId: "qatar",
    groupId: "group-a",
    stadiumId: "al-bayt-stadium",
    startDate: new Date("2022-11-29T18:00:00"),
    stageId: "group",
  },
  /* --- Group B --- */
  {
    homeTeamId: "england",
    awayTeamId: "iran",
    groupId: "group-b",
    stadiumId: "khalifa-international-stadium",
    startDate: new Date("2022-11-21T16:00:00"),
    stageId: "group",
  },
  {
    homeTeamId: "usa",
    awayTeamId: "wales",
    groupId: "group-b",
    stadiumId: "ahmad-bin-ali-stadium",
    startDate: new Date("2022-11-21T22:00:00"),
    stageId: "group",
  },
  {
    homeTeamId: "wales",
    awayTeamId: "iran",
    groupId: "group-b",
    stadiumId: "ahmad-bin-ali-stadium",
    startDate: new Date("2022-11-25T13:00:00"),
    stageId: "group",
  },
  {
    homeTeamId: "england",
    awayTeamId: "usa",
    groupId: "group-b",
    stadiumId: "al-bayt-stadium",
    startDate: new Date("2022-11-25T22:00:00"),
    stageId: "group",
  },
  {
    homeTeamId: "wales",
    awayTeamId: "england",
    groupId: "group-b",
    stadiumId: "ahmad-bin-ali-stadium",
    startDate: new Date("2022-11-29T22:00:00"),
    stageId: "group",
  },
  {
    homeTeamId: "iran",
    awayTeamId: "usa",
    groupId: "group-b",
    stadiumId: "al-thumama-stadium",
    startDate: new Date("2022-11-29T22:00:00"),
    stageId: "group",
  },
  /* --- Group C --- */
  {
    homeTeamId: "argentina",
    awayTeamId: "saudi-arabia",
    groupId: "group-c",
    stadiumId: "lusail-iconic-stadium",
    startDate: new Date("2022-11-22T13:00:00"),
    stageId: "group",
  },
  {
    homeTeamId: "mexico",
    awayTeamId: "poland",
    groupId: "group-c",
    stadiumId: "stadium-974",
    startDate: new Date("2022-11-22T19:00:00"),
    stageId: "group",
  },
  {
    homeTeamId: "poland",
    awayTeamId: "saudi-arabia",
    groupId: "group-c",
    stadiumId: "education-city-stadium",
    startDate: new Date("2022-11-26T16:00:00"),
    stageId: "group",
  },
  {
    homeTeamId: "argentina",
    awayTeamId: "mexico",
    groupId: "group-c",
    stadiumId: "lusail-iconic-stadium",
    startDate: new Date("2022-11-26T22:00:00"),
    stageId: "group",
  },
  {
    homeTeamId: "poland",
    awayTeamId: "argentina",
    groupId: "group-c",
    stadiumId: "stadium-974",
    startDate: new Date("2022-11-30T22:00:00"),
    stageId: "group",
  },
  {
    homeTeamId: "saudi-arabia",
    awayTeamId: "mexico",
    groupId: "group-c",
    stadiumId: "lusail-iconic-stadium",
    startDate: new Date("2022-11-30T22:00:00"),
    stageId: "group",
  },
  /* --- Group E --- */
  {
    homeTeamId: "germany",
    awayTeamId: "japan",
    groupId: "group-e",
    stadiumId: "khalifa-international-stadium",
    startDate: new Date("2022-11-23T16:00:00"),
    stageId: "group",
  },
  {
    homeTeamId: "spain",
    awayTeamId: "costa-rica",
    groupId: "group-e",
    stadiumId: "al-thumama-stadium",
    startDate: new Date("2022-11-23T19:00:00"),
    stageId: "group",
  },
  {
    homeTeamId: "japan",
    awayTeamId: "costa-rica",
    groupId: "group-e",
    stadiumId: "ahmad-bin-ali-stadium",
    startDate: new Date("2022-11-27T13:00:00"),
    stageId: "group",
  },
  {
    homeTeamId: "spain",
    awayTeamId: "germany",
    groupId: "group-e",
    stadiumId: "al-bayt-stadium",
    startDate: new Date("2022-11-27T22:00:00"),
    stageId: "group",
  },
  {
    homeTeamId: "japan",
    awayTeamId: "spain",
    groupId: "group-e",
    stadiumId: "khalifa-international-stadium",
    startDate: new Date("2022-12-01T22:00:00"),
    stageId: "group",
  },
  {
    homeTeamId: "costa-rica",
    awayTeamId: "germany",
    groupId: "group-e",
    stadiumId: "al-bayt-stadium",
    startDate: new Date("2022-12-01T22:00:00"),
    stageId: "group",
  },
  /* --- Group F --- */
  {
    homeTeamId: "morocco",
    awayTeamId: "croatia",
    groupId: "group-f",
    stadiumId: "al-bayt-stadium",
    startDate: new Date("2022-11-23T13:00:00"),
    stageId: "group",
  },
  {
    homeTeamId: "belgium",
    awayTeamId: "canada",
    groupId: "group-f",
    stadiumId: "ahmad-bin-ali-stadium",
    startDate: new Date("2022-11-23T22:00:00"),
    stageId: "group",
  },
  {
    homeTeamId: "belgium",
    awayTeamId: "morocco",
    groupId: "group-f",
    stadiumId: "al-thumama-stadium",
    startDate: new Date("2022-11-27T16:00:00"),
    stageId: "group",
  },
  {
    homeTeamId: "croatia",
    awayTeamId: "canada",
    groupId: "group-f",
    stadiumId: "khalifa-international-stadium",
    startDate: new Date("2022-11-27T19:00:00"),
    stageId: "group",
  },
  {
    homeTeamId: "croatia",
    awayTeamId: "belgium",
    groupId: "group-f",
    stadiumId: "ahmad-bin-ali-stadium",
    startDate: new Date("2022-12-01T18:00:00"),
    stageId: "group",
  },
  {
    homeTeamId: "canada",
    awayTeamId: "morocco",
    groupId: "group-f",
    stadiumId: "al-thumama-stadium",
    startDate: new Date("2022-12-01T18:00:00"),
    stageId: "group",
  },
  /* --- Group G --- */
  {
    homeTeamId: "switzerland",
    awayTeamId: "cameroon",
    groupId: "group-g",
    stadiumId: "al-janoub-stadium",
    startDate: new Date("2022-11-24T13:00:00"),
    stageId: "group",
  },
  {
    homeTeamId: "brazil",
    awayTeamId: "serbia",
    groupId: "group-g",
    stadiumId: "lusail-iconic-stadium",
    startDate: new Date("2022-11-24T22:00:00"),
    stageId: "group",
  },
  {
    homeTeamId: "cameroon",
    awayTeamId: "serbia",
    groupId: "group-g",
    stadiumId: "al-janoub-stadium",
    startDate: new Date("2022-11-28T13:00:00"),
    stageId: "group",
  },
  {
    homeTeamId: "brazil",
    awayTeamId: "switzerland",
    groupId: "group-g",
    stadiumId: "stadium-974",
    startDate: new Date("2022-11-28T19:00:00"),
    stageId: "group",
  },
  {
    homeTeamId: "serbia",
    awayTeamId: "switzerland",
    groupId: "group-g",
    stadiumId: "stadium-974",
    startDate: new Date("2022-12-02T22:00:00"),
    stageId: "group",
  },
  {
    homeTeamId: "cameroon",
    awayTeamId: "brazil",
    groupId: "group-g",
    stadiumId: "lusail-iconic-stadium",
    startDate: new Date("2022-12-02T22:00:00"),
    stageId: "group",
  },
  /* --- Group H --- */
  {
    homeTeamId: "uruguay",
    awayTeamId: "south-korea",
    groupId: "group-h",
    stadiumId: "education-city-stadium",
    startDate: new Date("2022-11-24T16:00:00"),
    stageId: "group",
  },
  {
    homeTeamId: "portugal",
    awayTeamId: "ghana",
    groupId: "group-h",
    stadiumId: "stadium-974",
    startDate: new Date("2022-11-24T19:00:00"),
    stageId: "group",
  },
  {
    homeTeamId: "south-korea",
    awayTeamId: "ghana",
    groupId: "group-h",
    stadiumId: "education-city-stadium",
    startDate: new Date("2022-11-28T16:00:00"),
    stageId: "group",
  },
  {
    homeTeamId: "portugal",
    awayTeamId: "uruguay",
    groupId: "group-h",
    stadiumId: "lusail-iconic-stadium",
    startDate: new Date("2022-11-28T22:00:00"),
    stageId: "group",
  },
  {
    homeTeamId: "ghana",
    awayTeamId: "uruguay",
    groupId: "group-h",
    stadiumId: "al-janoub-stadium",
    startDate: new Date("2022-12-02T18:00:00"),
    stageId: "group",
  },
  {
    homeTeamId: "south-korea",
    awayTeamId: "portugal",
    groupId: "group-h",
    stadiumId: "education-city-stadium",
    startDate: new Date("2022-12-02T18:00:00"),
    stageId: "group",
  },
];

const seedPlayoffMatches = [
  {
    playoffId: "round-of-16",
    stadiumId: "khalifa-international-stadium",
    startDate: new Date("2022-12-03T18:00:00"),
    stageId: "playoff",
  },
  {
    playoffId: "round-of-16",
    stadiumId: "ahmad-bin-ali-stadium",
    startDate: new Date("2022-12-03T22:00:00"),
    stageId: "playoff",
  },
  {
    playoffId: "round-of-16",
    stadiumId: "al-thumama-stadium",
    startDate: new Date("2022-12-04T18:00:00"),
    stageId: "playoff",
  },
  {
    playoffId: "round-of-16",
    stadiumId: "al-bayt-stadium",
    startDate: new Date("2022-12-04T22:00:00"),
    stageId: "playoff",
  },
  {
    playoffId: "round-of-16",
    stadiumId: "al-janoub-stadium",
    startDate: new Date("2022-12-05T18:00:00"),
    stageId: "playoff",
  },
  {
    playoffId: "round-of-16",
    stadiumId: "stadium-974",
    startDate: new Date("2022-12-05T22:00:00"),
    stageId: "playoff",
  },
  {
    playoffId: "round-of-16",
    stadiumId: "education-city-stadium",
    startDate: new Date("2022-12-06T18:00:00"),
    stageId: "playoff",
  },
  {
    playoffId: "round-of-16",
    stadiumId: "lusail-iconic-stadium",
    startDate: new Date("2022-12-06T22:00:00"),
    stageId: "playoff",
  },

  {
    playoffId: "quarter-finals",
    stadiumId: "education-city-stadium",
    startDate: new Date("2022-12-09T18:00:00"),
    stageId: "playoff",
  },
  {
    playoffId: "quarter-finals",
    stadiumId: "lusail-iconic-stadium",
    startDate: new Date("2022-12-09T22:00:00"),
    stageId: "playoff",
  },
  {
    playoffId: "quarter-finals",
    stadiumId: "al-thumama-stadium",
    startDate: new Date("2022-12-10T18:00:00"),
    stageId: "playoff",
  },
  {
    playoffId: "quarter-finals",
    stadiumId: "al-bayt-stadium",
    startDate: new Date("2022-12-10T22:00:00"),
    stageId: "playoff",
  },

  {
    playoffId: "semi-finals",
    stadiumId: "lusail-iconic-stadium",
    startDate: new Date("2022-12-13T22:00:00"),
    stageId: "playoff",
  },
  {
    playoffId: "semi-finals",
    stadiumId: "al-bayt-stadium",
    startDate: new Date("2022-12-14T22:00:00"),
    stageId: "playoff",
  },

  {
    playoffId: "third-place",
    stadiumId: "khalifa-international-stadium",
    startDate: new Date("2022-12-17T18:00:00"),
    stageId: "playoff",
  },

  {
    playoffId: "final",
    stadiumId: "lusail-iconic-stadium",
    startDate: new Date("2022-12-18T18:00:00"),
    stageId: "playoff",
  },
];

const seedUserMatches = ({
  users,
  matches,
}: {
  users: User[];
  matches: Match[];
}) => {
  const userMatches: { userId: string; matchId: number }[] = [];

  for (const user of users) {
    for (const match of matches) {
      userMatches.push({ userId: user.id, matchId: match.id });
    }
  }

  return userMatches;
};

const seedUserTeams = ({ users, teams }: { users: User[]; teams: Team[] }) => {
  const userTeams: {
    userId: string;
    teamId: string;
    points: number;
    goalDifference: number;
  }[] = [];

  for (const user of users) {
    for (const team of teams) {
      userTeams.push({ userId: user.id, teamId: team.id, ...seedUserTeam });
    }
  }

  return userTeams;
};

const seedUserRanking = ({ users }: { users: User[] }) => {
  const userRanking: {
    userId: string;
    groupPoints: number;
    playoffPoints: number;
    totalPoints: number;
  }[] = [];

  for (const user of users) {
    userRanking.push({ userId: user.id, ...seedRanking });
  }

  return userRanking;
};

const seedTournamentMatches = ({ matches }: { matches: Match[] }) => {
  const tournamentMatches: { matchId: number }[] = [];

  for (const match of matches) {
    tournamentMatches.push({ matchId: match.id });
  }

  return tournamentMatches;
};

async function seed() {
  // /* Utworzenie stadionów */
  // await db.stadium.createMany({ data: seedStadiums });
  // /* Utworzenie etapów */
  // await db.stage.createMany({ data: seedStages });
  // /* Utworzenie grup */
  // await db.group.createMany({ data: seedGroups });
  // /* Utworzenie playoffów */
  // await db.playoff.createMany({ data: seedPlayoffs });
  // /* Utworzenie drużyn */
  // await db.team.createMany({ data: seedTeams });
  // /* Utworzenie piłkarzy */
  // await db.player.createMany({ data: seedPlayers });
  // /* Utworzenie meczów grupowych i playoff */
  // await db.match.createMany({
  //   data: [...seedGroupMatches, ...seedPlayoffMatches],
  // });

  /* Pobranie użytkowników, meczów, drużyn */
  // const users = await db.user.findMany();
  const matches = await db.match.findMany();
  // const teams = await db.team.findMany();

  // /* Utworzenie rankingów dla użytkowników */
  // const userRanking = await Promise.all(seedUserRanking({ users }));
  // await db.userRanking.createMany({ data: userRanking });

  // /* Utworzenie meczów dla użytkowników */
  // const userMatches = await Promise.all(seedUserMatches({ users, matches }));
  // await db.userMatch.createMany({ data: userMatches });

  // /* Utworzenie drużyn dla użytkowników */
  // const userTeams = await Promise.all(seedUserTeams({ users, teams }));
  // await db.userTeam.createMany({ data: userTeams });

  /* Utworzenie wyników spotkań dla turnieju */
  const tournamentMatches = await Promise.all(
    seedTournamentMatches({ matches })
  );
  await db.tournamentMatch.createMany({ data: tournamentMatches });
}

seed();
